lanquage: php
php:
- '7.1'

install:
- composer self-update
- make install

script: make lint
before_script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
